# Generated by Django 5.2.1 on 2025-05-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_transacao_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('REC', 'Receita'), ('DSP', 'Despesa')], max_length=3),
        ),
    ]
